### ISSUE TITLE
你好！ 有没有完整的数据集

### ISSUE THREAD

**Issue by shenliaoxx** [Jiani-CAO/WETrak#1]

**Comment by Jiani-CAO** [comment]
Thank you for your interest! 

The data of user1 is in [dropbox](https://www.dropbox.com/scl/fi/joutkpriwyvtg5oavg53e/user1.zip?rlkey=vf50kzgy25545ie6dnqgad8mt&st=91tj0q6y&dl=0), which includes the raw data as well as the train and test data obtained after running ''preprocess_data.ipynb''. 

Note that the model in the paper is personalized, meaning a separate model is trained for each individual. 

I hope this can help you!
